[package]
name = "terravoxel"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_math = { version = "0.16", default-features = false, features = ["curve"] }
bevy_mesh = { version = "0.16", default-features = false }
bevy_render = { version = "0.16", default-features = false }
bevy_pbr = { version = "0.16", default-features = false }
bevy_platform = { version = "0.16", default-features = false }
arrayvec = { version = "0.7.6", default-features = false }
thiserror = "2.0.12"
serde = { version = "1", default-features = false, features = [
  "derive",
], optional = true }

[dev-dependencies]
# for examples
bevy = "0.16"

[features]
default = ["std", "serialize"]
std = ["bevy_platform/std", "serde?/std"]
serialize = ["dep:serde", "bevy_math/serialize"]

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 1

[profile.release]
# Maximum Link Time Optimization for best performance
lto = "fat"
# Single codegen unit maximizes optimization opportunities
codegen-units = 1
# Disable incremental compilation for maximum optimization
incremental = false
opt-level = 3

[build]
rustflags = ["-O"]


[lints.clippy]
doc_markdown = "warn"
manual_let_else = "warn"
match_same_arms = "warn"
redundant_closure_for_method_calls = "warn"
redundant_else = "warn"
semicolon_if_nothing_returned = "warn"
type_complexity = "allow"
undocumented_unsafe_blocks = "warn"
unwrap_or_default = "warn"
needless_lifetimes = "allow"
too_many_arguments = "allow"
nonstandard_macro_braces = "warn"

ptr_as_ptr = "warn"
ptr_cast_constness = "warn"
ref_as_ptr = "warn"

too_long_first_doc_paragraph = "allow"

std_instead_of_core = "warn"
std_instead_of_alloc = "warn"
alloc_instead_of_core = "warn"

allow_attributes = "warn"
allow_attributes_without_reason = "warn"

[lints.rust]
missing_docs = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(docsrs_dep)'] }
unsafe_op_in_unsafe_fn = "warn"
unused_qualifications = "warn"
